define(function(require, exports, module) {
    require('./index.css');
    module.exports = Vue.component('index', {
        template: ['<div>',
            '  <el-tabs v-model="activeName">',
            '    <el-tab-pane border label="抓图" name="first">',
            '      <el-tabs type="card" v-model="secondName">',
            '        <el-tab-pane label="抓图计划" name="first">',
            '          <div style="margin-top: 10px;">',
            '            <el-select size="mini" v-model="test">',
            '               <el-option label="定时" value="定时"></el-option>',
            '            </el-select>',
            '            <el-button size="mini" icon="el-icon-error" type="danger">删除</el-button>',
            '            <el-button size="mini" icon="el-icon-delete-solid" type="primary">删除全部</el-button>',
            '            <el-button size="mini" @click="dialogVisible = true">高级参数</el-button>',
            '          </div>',
            '          <div>',
            '            <div style="margin-top: 10px;">',
            '              <span>',
            '                <span class="square red"></span>',
            '                <span>定时</span>',
            '              </span>',
            '            </div>',
            '            <div class="m-wrap">',
            '              <label for="">星期一</label>',
            '              <div class="m-row">',
            '                <div class="items-box" v-for="(item, index) in time" :key="index" >',
            '                  <span class="m-num">{{ item }}</span>',
            '                  <p v-if="index !== (time.length - 1)" class="items white"></p>',
            '                </div>',
            '              </div>',
            '            </div>',
            '            <div class="m-wrap">',
            '              <label for="">星期二</label>',
            '              <div class="m-row">',
            '                <div class="items-box" v-for="(item, index) in time" :key="index">',
            '                  <span class="m-num">{{ item }}</span>',
            '                  <p v-if="index !== (time.length - 1)" class="items white"></p>',
            '                </div>',
            '              </div>',
            '            </div>',
            '            <div class="m-wrap">',
            '              <label for="">星期三</label>',
            '              <div class="m-row">',
            '                <div class="items-box" v-for="(item, index) in time" :key="index">',
            '                  <span class="m-num">{{ item }}</span>',
            '                  <p v-if="index !== (time.length - 1)" class="items white"></p>',
            '                </div>',
            '              </div>',
            '            </div>',
            '          </div>',
            '        </el-tab-pane>',
            '        <el-tab-pane label="抓图参数" name="second">',
            '          <p style="margin: 0px 0 10px ;" class="p-title">定时</p>',
            '          <el-checkbox v-model="check">启用定时抓图</el-checkbox>',
            '          <div class="basic-item-box">',
            '            <label for="">图片格式</label>',
            '            <el-select class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">分辨率</label>',
            '            <el-select class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">图片质量</label>',
            '            <el-select class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">抓图间隔</label>',
            '            <el-input style="width: 230px;" disabled size="mini" v-model="test"></el-input>',
            '            <el-select style="width: 230px;" class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          ',
            '          <p style="margin: 10px 0px ;" class="p-title">事件触发</p>',
            '          <el-checkbox v-model="check">启用事件抓图</el-checkbox>',
            '          <div class="basic-item-box">',
            '            <label for="">图片格式</label>',
            '            <el-select class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">分辨率</label>',
            '            <el-select class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">图片质量</label>',
            '            <el-select class="basic-input" size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">抓图间隔</label>',
            '            <el-input style="width: 230px;"  disabled size="mini" v-model="test"></el-input>',
            '            <el-select style="width: 230px;"  size="mini" v-model="test">',
            '              <el-option label="北京" value="beijing"></el-option>',
            '            </el-select>',
            '          </div>',
            '          <div class="basic-item-box">',
            '            <label for="">抓图数量</label>',
            '            <el-input class="basic-input" disabled size="mini" v-model="test"></el-input>',
            '          </div>',
            '          <div style="text-align: center; margin-top: 10px;">',
            '            <el-button icon="el-icon-receiving" size="mini" type="success">保存</el-button>',
            '          </div>',
            '        </el-tab-pane>',
            '      </el-tabs>',
            '    </el-tab-pane>',
            '  </el-tabs>',
            '  ',
            '  <el-dialog title="高级参数" :visible.sync="dialogVisible" width="400px">',
            '    <div class="basic-item-box">',
            '      <label for="">流码类型</label>',
            '      <el-select size="mini" v-model="test">',
            '        <el-option label="北京" value="beijing"></el-option>',
            '      </el-select>',
            '    </div>',
            '    <span slot="footer" class="dialog-footer">',
            '      <el-button @click="dialogVisible = false">取 消</el-button>',
            '      <el-button type="primary" @click="dialogVisible = false">确 定</el-button>',
            '    </span>',
            '  </el-dialog>',
            '</div>',
        ].join(""),
        data: function() { // 数据
            return {
                activeName: 'first',
                secondName: 'first',
                test: '',
                check: true,
                time: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24],
                dialogVisible: false
            }
        },
        methods: {}
    })
})
